//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Invoice", typeof(Invoice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No invoice.
        /// </summary>
        public static string Empty_invoice {
            get {
                return ResourceManager.GetString("Empty_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string Format_days {
            get {
                return ResourceManager.GetString("Format_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Format_money {
            get {
                return ResourceManager.GetString("Format_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice_{0}.txt.
        /// </summary>
        public static string Invoice_filename {
            get {
                return ResourceManager.GetString("Invoice_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-30} {1}: {2}.
        /// </summary>
        public static string Invoice_item_format {
            get {
                return ResourceManager.GetString("Invoice_item_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice nr {0}.
        /// </summary>
        public static string Invoice_title {
            get {
                return ResourceManager.GetString("Invoice_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty points earned: {0}.
        /// </summary>
        public static string Total_loyalty_points {
            get {
                return ResourceManager.GetString("Total_loyalty_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price: {0}.
        /// </summary>
        public static string Total_price {
            get {
                return ResourceManager.GetString("Total_price", resourceCulture);
            }
        }
    }
}
